version: "3.9"
services:
  go2py-dev:
    build: .
    container_name: go2py-dev
    network_mode: host
    privileged: true
    command: bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/home/Go2Py
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    runtime: nvidia
    stdin_open: true
    tty: true